linters:
    enable-all: true
    disable:
      - depguard
      - gci
      - exhaustruct
      - gofumpt
      - varnamelen
      - wrapcheck
      - lll
      - forcetypeassert 
      - interfacebloat
      - err113
      - intrange
      - gocritic


